name: CICD

on:
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan_build_push_sign_and_notify:
    runs-on: ubuntu-latest
    container:
        image: docker:24.0.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'report.txt'
          severity: 'CRITICAL'

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            Scan failed - Fred
            Failed trivy scan, see uploaded report.

      - name: Upload report to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNELID }}
          file_path: "report.txt"
          initial_comment: 'post by slack-upload-file'

      - name: Install Cosign
        if: success()
        uses: sigstore/cosign-installer@v3.1.2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_MESSAGE: |
              Images built and signed
              Name: Li Hao
              Metriculation: ${{ secrets.METRICULATION }}
              Email: ${{ secrets.EMAIL }}
              Git: https://github.com/CH4NGEbetter/CICD.git
              Image: https://hub.docker.com/r/ch4ngebetter/app

